### ISSUE TITLE
Printing git version blocks building release archives

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/rmb-rs#126]
I tried building the source contained in one of the release archives (for [example](https://github.com/threefoldtech/rmb-rs/archive/refs/tags/v1.0.2.tar.gz)). It fails [here](https://github.com/threefoldtech/rmb-rs/blob/df4543831ab173a814397aa693827d545e727baf/build.rs#L4) in `build.rs` when running the `git_version` macro because in this case the directory is not actually a Git repo.

Suggest to adding some logic to skip this or ignore the error when building without Git.

**Comment by xmonader** [comment]
Is there a specific reason to not use the bundled binaries in the release?
I'd still clone and switch to the proper tag to build (even in a CI/CD)

**Comment by scottyeager** [comment]
Not saying there's any particularly good reason to do this--just noting that the source archives won't build as is.

I see that the build instructions specify cloning with Git, so maybe the answer is just that it's a build requirement and users should check the docs. Still, would be nice to at least present a helpful error in case someone tries to download and build these archives in the future.

**Comment by xmonader** [comment]
Also not sure if similar approach may help 
https://github.com/threefoldtech/rfs/blob/master/build.rs
```
fn main() {
    println!(
        "cargo:rustc-env=GIT_VERSION={}",
        git_version::git_version!(args = ["--tags", "--always", "--dirty=-modified"], fallback = "unknown")
    );
}
```

**Comment by scottyeager** [comment]
> Also not sure if similar approach may help

This did the trick :+1:
