### ISSUE TITLE
rmb deep documentation in mdbook

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/rmb-rs#138]
- describe messages of rmb
- how does it work
- how to use from V (is V compatible with latest version)
- how is security done
- how is redundancy

make sure mdbook gets deployed as described on spiderlib

**Comment by xmonader** [comment]
first two parts are addressed in https://www2.manual.grid.tf/internals/internals.html

more elaboration need to happen on the security part, and redundancy needs to be resolved first
