### ISSUE TITLE
RMB redundancy & 3bot integration

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/rmb-rs#140]
- see how 3bots can talk to each other over rmb (no local rmb components needed)
- describe in manual of 3bot (web3gw)
- make sure its always redundant, so even when rmb server falls away it still works, client has support for it in V

**Comment by muhamadazmy** [comment]
The rmb-peer component (the local component) only implement the protocol and provide a simpler all json implementation for languages that cannot implement the protcol itself. Other systems (terraform for example) directly connects to rmb without the need for an intermediate gateway (the rmb-peer).

This mean to allow 3bots to talk directly with no rmb-peer we need to implement the protocol in a V sdk. I have never used V but i think the challenging part can be:
- Have protobuf support
- Have websocket support

I will talk to the team about it and see what can be done.

**Comment by muhamadazmy** [comment]
yeah the `rmb-peer` is the rmb server as you describe above. it does everything on the client behalf as described in documentation

**Comment by xmonader** [comment]
https://github.com/threefoldtech/rmb-rs/issues/141
