### ISSUE TITLE
Error while serving HTTP connection: error shutting down connection: Socket not connected (os error 107)

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/rmb-rs#146]
Shows in both relay instances for dev and qa networks

![image](https://github.com/threefoldtech/rmb-rs/assets/42457449/e103a8f3-6de2-494e-80da-47d38b4c0cfa)

**Comment by xmonader** [comment]
Could that be cause by a non reconnecting websocket coming from javascript?

**Comment by muhamadazmy** [comment]
I have never seen this, can u describe the setup where this happened

**Comment by sameh-farouk** [comment]
> I have never seen this, can u describe the setup where this happened

dev and qa networks public relays
