### ISSUE TITLE
add support for multiple `substrate` urls

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/rmb-rs#150]
Right now rmb accepts a single chain (substrate) urls which is used mainly for twin queries to verify signatures. We need to be able to provide multiple urls in case one of them is down. Hence rmb can then try multiple backends in case one of them is failing

**Comment by MarioBassem** [comment]
updated implementation to accept multiple substrate urls, but still needs to be tested.

**Comment by muhamadazmy** [comment]
@MarioBassem this can be easily tested because we already have multiple public nodes for mainnet

check here
https://github.com/threefoldtech/zos/blob/main/pkg/environment/environment.go#L113
