### ISSUE TITLE
Clarify the error 102 message.

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/rmb-rs#174]
we have faced this error recently and the error message wasn't clear
![Screenshot from 2023-11-12 11-33-30](https://github.com/threefoldtech/rmb-rs/assets/62248851/2e6b90b4-419c-4adf-93e0-5d20a5875d3f)

https://github.com/threefoldtech/rmb-rs/blob/3a2166459eeeb4782648c7f79ba80fe4da22d68f/src/types/mod.rs#L35

we can make the error more descriptive and mention that the ttl or massage expired

**Comment by muhamadazmy** [comment]
I really think this is just a problem with the implementation of the client. The error response in the envelope might have a code, but will always have an error message explaining what happened.

**Comment by 0oM4R** [comment]
> I really think this is just a problem with the implementation of the client. The error response in the envelope might have a code, but will always have an error message explaining what happened.

the error we got in the client is just `code: 102`

 
https://github.com/threefoldtech/tfgrid-sdk-ts/blob/704e339146c90253c9d582fb4ebd70bcb903e054/packages/rmb_direct_client/lib/client.ts#L332

i tried to log the envelop.error and got the same message:
![Screenshot from 2023-11-16 11-10-29](https://github.com/threefoldtech/rmb-rs/assets/62248851/c2ce811e-2c52-4a17-b9c5-8f6af01ac4c2)

**Comment by muhamadazmy** [comment]
That is so weird, I will take another look.

**Comment by muhamadazmy** [comment]
@0oM4R 
Can you explain to me where the `Error` object in the screenshot above is coming from ? because that's not what rmb sends back. this has been constructed somewhere else in the code from the original response
