### ISSUE TITLE
Some Nodes on mainnet are unreachable (To be verified on mainnet)

### ISSUE THREAD

**Issue by Eslam-Nawara** [threefoldtech/rmb-rs#175]
While trying to batch deploy 1000 nodes on mainnet, some nodes were up but not reachable through rmb
It might get solved with the newer version 1.1.1

root cause of https://github.com/threefoldtech/zos/issues/2060

**Comment by scottyeager** [comment]
Have been tracking this issue here: https://github.com/threefoldtech/zos/issues/2060
