### ISSUE TITLE
The public keys generated for the twin by the mnemonic and its seed are different

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/rmb-rs#181]
I have a mnemonic and generate the seed with the substrate tool (subkey)

### Steps
1- Run rmb-peer using the mnemonic, it will load the twin

![image](https://github.com/threefoldtech/rmb-rs/assets/41957921/aab8c862-92e9-42fa-96a7-c947d20b6104)

2- Wait for a minute 
3- Run rmb-peer using the seed of the used mnemonic in the previous step, it will also load the same twin but it will update the twin's public key

![image](https://github.com/threefoldtech/rmb-rs/assets/41957921/f3dfc830-718c-42ea-b2f0-20710699cb58)

### Expected Results

Using the mnemonic or the seed for the same twin should result in the same public key

### Findings

- When we use the mnemonic, it tries to get the seed with bip39 which is different than the seed we got from subkey tool.
- Also if you used the seed from bip93, it will lead to `no twin found on this network with given key`
https://github.com/threefoldtech/rmb-rs/blob/15b8be8cea40acf762fb83b94328944c41cc9414/src/peer/e2e/mod.rs#L38

**Comment by muhamadazmy** [comment]
Also a side note

Since `zos` always use the seeds (not the mnemonics) it means that all zos nodes will have to update their twins if this fix is deployed

**Comment by AhmedHanafy725** [comment]
> Also a side note
> 
> Since `zos` always use the seeds (not the mnemonics) it means that all zos nodes will have to update their twins if this fix is deployed

as discussed with @muhamadazmy, the peers that are using the seed won't be affected by this change because the seed is used as is, only the peers that are using the mnemonic will need to update the twin as it needs to convert the mnemonic to a seed. So for the zos nodes, nothing will be changed.

**Comment by muhamadazmy** [comment]
@AhmedHanafy725 you are absolutely correct. I got it wrong.

**Comment by ashraffouda** [comment]
https://github.com/threefoldtech/rmb-rs/pull/183/files
