### ISSUE TITLE
relay info is not set for this twin

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/rmb-rs#182]
trying to send an envelope to a node results in

![Screenshot from 2023-12-14 14-59-25](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/b57f0985-5984-41e5-83ca-88f97db6bd6f)

twin id: 800 
net: dev

this twin already has the info on the chain

![image](https://github.com/threefoldtech/rmb-rs/assets/41957921/4a2a62cd-11c1-4f75-910f-34de28908a6a)

note that graphql was down at that time.

**Comment by muhamadazmy** [comment]
The relay will only send this back if you are trying to send a message to a remote twin that has it's relay not set. This issue is with the destination twin, not the source. the question is twin 800 the source twin or the destination twin?

**Comment by 0oM4R** [comment]
> The relay will only send this back if you are trying to send a message to a remote twin that has it's relay not set. This issue is with the destination twin, not the source. the question is twin 800 the source twin or the destination twin?


twin 800 is the source twin

**Comment by muhamadazmy** [comment]
And what is the destination twin? and does it have a relay set ?

**Comment by muhamadazmy** [comment]
Both twin 17 and 21 on devnet has relay. I am not sure if this is still an issue or not.  Pleas reopen if that is still an issue
