### ISSUE TITLE
peers on different relays can't call each other

### ISSUE THREAD

**Issue by Omarabdul3ziz** [threefoldtech/rmb-rs#192]
the issue appeared on the proxy with twin running on `relay.bknd1.ninja.tf` can't reach nodes running on `relay.grid.tf`. [more details](https://github.com/threefoldtech/tfgrid-sdk-go/issues/644#issuecomment-1987299961)

**Comment by muhamadazmy** [comment]
Relay need to verify the twin data so that:
- If destination twin has empty relays list, it need to return an immediate error to sender
- If relay is an ip (not a dns name) this means twin has out-dated data and need to be treated as if it has no relays

**Comment by Omarabdul3ziz** [comment]
what we noticed is:
- relay federation works on other networks 
  tried to use gridproxy on test net https://gridproxy.02.test.grid.tf/ to call nodes with relay `relay.test.grid.tf` and it works fine
  but on mainnet from ninja relay to relay.grid.tf or from relay.02.grid.tf to relay.grid.tf it timeout

- just noticed also if on mainnet calls from peer on `relay.bknd1.ninja.tf` to `relay.02.grid.tf` fails with this error
  ```
  relays '["relay.grid.tf"]' was not reachable in time
  ```
  knowing that `relay.grid.tf` is not the relay for any of the two peers

**Comment by sameh-farouk** [comment]
> Versions
> relay1 >> relay.grid.tf deployed with version 1.0.5
> relay2 >> relay.02.grid.tf deployed with version 1.2.1
> ninja relay >> relay.bknd1.ninja.tf deployed with version 1.2.1

> Issue
> federation doesn't work properly between different relays if one of them was relay1:

> ninja relay to relay1 fails
> relay2 to relay1 fails

Starting from Relay version 1.1.0, there were changes to the federation logic, and it transitioned from RMB to the relay. Federation between versions prior to and after this specific version is not supported. In general, it is expected for relays within the same network to run the same version.

**Comment by Omarabdul3ziz** [comment]
federation works fine now after upgrading relay.grid.tf to 1.2.1
