### ISSUE TITLE
HTTP workers should retry on 5xx HTTP errors too

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/rmb-rs#60]
are there any reasons for not retrying a 5xx error?
5xx error codes should be retried as those are server errors. They could be short-term (busy server, etc) except for maybe 501 and 505.

**Comment by muhamadazmy** [comment]
Actually I am not sure about this one. retrying on an 5xx is not likely to be fix the issue. I would rather have a consistent behavior than special edge cases.
