### ISSUE TITLE
document file uploads and add integration tests

### ISSUE THREAD

**Issue by abom** [threefoldtech/rmb-rs#80]
Related issues

* #77

**Comment by abom** [comment]
I added some tests, at first, it mostly failed because of the following error

```
failed to deliver message to remote rmb: error writing a body to connection: Broken pipe (os error 32): Broken pipe (os error 32)
```

I thought it's the timing and we should wait for rmb instance (other end), but found out we retry if we got `405 Method Not Allowed`, so I just returned a `Terminal` error to stop retrying, it's now better and the test passes most of the times, but still getting this `broken pipe` randomly.

Another concern is the number if redis container we start for tests, while IMO, we can leverage the storage prefixes to use the same redis instance.

**Comment by mohamedamer453** [comment]
Docs for the File Uploads were added and integration tests were also added in #81 . but there are no docs on how to run these tests so i was not able to verify if these tests are working or not.

**Comment by mohamedamer453** [comment]
Verified.

I was able to run the tests using [` cargo test`](https://doc.rust-lang.org/cargo/guide/tests.html) and all the added tests ran without any issues.

![image](https://user-images.githubusercontent.com/101194226/187069264-090182a2-fb16-481a-88c2-7b3ba6048e5d.png)

and the docs on how to run the tests will be followed in #86
